e2e: fix "Failed to compile e2e"
Got lots of errors when run "make run-e2e" like below
```
Failed to compile e2e:

/root/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.2.11/framework/cluster_helpers.go:231:12: cannot use input.Client (variable of type client.Client) as type Getter in struct literal:
	client.Client does not implement Getter (wrong type for Get method)
		have Get(ctx context.Context, key "k8s.io/apimachinery/pkg/types".NamespacedName, obj client.Object, opts ...client.GetOption) error
		want Get(ctx context.Context, key "k8s.io/apimachinery/pkg/types".NamespacedName, obj client.Object) error
```

The issue is because of one of the break changes between controller-runtime 0.12 and 0.13
see https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.13.0

It can be fixed by downgrading sigs.k8s.io/controller-runtime from 0.13.1 to 0.12.3